config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :projects

root 'projects#index'
 get 'users' => 'users#index'
 get 'projects' => 'projects#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @project = Project.all
  end

  def new
    @project = Project.new
  end

  def edit

  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Product was successfully created.'}
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:project_name, :project_description, :project_image, :project_youtube_url)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @user = User.all
  end

  def new
    @user = User.new
  end

  def show
    @users = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user , notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :age,:email,:avatar_url,:linkedin_url,:behance_url,:github_url,:playstore_url,:twitter_url,:pinterest_url,:skills,:location,:course)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CfApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p id="notice" class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-info"><%= alert %></p>
    <% end %>
    <%= render partial: 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
<% if @project.errors.any? %>
		<div id="errors">
			<h4><%= pluralize(@project.errors.count, "error") %> prevented this post from saving:</h4>
			<ul>
				<% @project.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
<p>
  <%= f.label :project_name %>
  <%= f.text_field :project_name %>
</p>
<p>
  <%= f.label :project_description %>
  <%= f.text_area :project_description, class: "description" %>
</p>
<p>
	<%= f.label :project_image, class: "block" %>
	<%= f.file_field :project_image  %>
 </p>

<p>
  <%= f.submit class: 'button-primary' %>
</p>
<% end %>

app/views/projects/index.html.erb
<div class="project_wrapper">
<% @project.each do |project| %>
    <h4 class="title"><%= link_to project.project_name, project %></h4>
    <p class="date"><%= project.created_at.strftime("%B, %d, %Y") %></p>

    <% if project.project_image.present? %>
    <div class="index-image" style="background-image:url(<%= image_url (project.project_image) %>)"></div>
    <% else %>
  <% end %>
    <div class="u-cf"></div>
    <%= truncate project.project_description, length: 350 %>
<% end %>
</div>

app/views/projects/new.html.erb
<div class="container new-form">
  <section class="col col-md-6">
    <h1> New Project </h1>
    <%= render 'form' %>
  </section>
</div>

app/views/projects/show.html.erb
<div class="project_content">
  <% if @project.project_image.present? %>
  <%= image_tag @project.project_image, class: 'post-image' %>
  <% else %>
  <% end %>
  <h3 class="title">
    <%= @project.project_name %>
  </h3>
  <p class="date">
    Submitted <%= time_ago_in_words(@project.created_at) %> Ago
  </p>

  <%= link_to root_path(@project) do %>
    <button class="button">Back</button>
          <button class="btn btn-default"><%= link_to 'Edit', edit_project_path(@project)%></button>
  <% end %>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <figure class="logo">
      <%= image_tag ('logo.png') %>
    </figure>
    <ul>
      <li>
         <%= link_to "Projects",  projects_path %>
      </li>
      <li>
       <%= link_to 'New Project', new_project_path, :class => "new_project" %>
      </li>
      <li>
      <%= link_to 'New Student', new_user_path, :class => "new_user" %>
      </li>
      <li>
        <a href="#">Job List</a>
      </li>
      <li>
       <% if user_signed_in? %>
       <a><%= link_to current_user.first_name, user_path(current_user) %></a>
       <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="col-md-6">
    <div class="field">
      <p><%= f.label :avatar_url %></p>
      <p><%= f.text_area :avatar_url, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :first_name %></p>
      <p><%= f.text_field :first_name,class:  'form-control' %></p>
    </div>
    <div class="field">
      <p><%= f.label :last_name %></p>
      <p><%= f.text_area :last_name,class:  'form-control' %></p>
    </div>
    <div class="field">
      <p><%= f.label :course %></p>
      <p><%= f.select(:course, options_for_select([['Web Development','Web Development'],['UX Design','UX Design'],['UI Design','UI Design'],['IOS Development','IOS Development']]) ,{}, :class => 'form-control')  %></p>
    </div>
    <div class="field">
      <p><%= f.label :age %></p>
      <p><%= f.number_field(:age, in: 1.0..100.0,class:  'form-control') %></p>
    </div>
    <div class="field">
      <p><%= f.label :bio %></p>
      <p><%= f.text_area :bio, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :skills %></p>
      <p><%= f.text_area :skills, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :location %></p>
      <p><%= f.text_area :location, class: 'form-control'%></p>
    </div>
  </div>

  <div class="col-md-6">
    <div class="field">
      <p><%= f.label :email %></p>
      <p><%= f.text_area :email, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :linkedin_url %></p>
      <p><%= f.text_area :linkedin_url, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :behance_url %></p>
      <p><%= f.text_area :behance_url, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :github_url %></p>
      <p><%= f.text_area :github_url, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :playstore_url %></p>
      <p><%= f.text_area :playstore_url, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :twitter_url %></p>
      <p><%= f.text_area :twitter_url, class: 'form-control'%></p>
    </div>
    <div class="field">
      <p><%= f.label :pinterest_url %></p>
      <p><%= f.text_area :pinterest_url, class: 'form-control'%></p>
    </div>
    <div class="actions">
      <p><%= f.submit class: "btn btn-default" %></p>
    </div>
  </div>
  <% end %>

app/views/users/edit.html.erb
<div class="container listing-user">
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="user-index">
  <div class="container">
    <div class="row">
     <% @user.each do |u| %>
     <h1 class="user-title">Hello  <%= u.first_name %></h1>

      <div class="col-md-4">
        <section class="user-left">
          <div class="user-info">
          <% if u.avatar_url.present? %>
            <%= image_tag u.avatar_url, :class => 'user-img' %>
          <% else %>
          <% end %>
          <h3>First Name</h3>
          <p><%= u.first_name %></h2>
          <h3>Last Name</h3>
          <p><%= u.last_name %></p>
          <h3>Course</h3>
          <p><%= u.course %></p>
          <h3>Age</h3>
          <p><%= u.age %></p>
          <h3>Location</h3>
          <p><%= u.location %></p>
        </div>
        <div class="user-links">
          <p class="user-links-round icon-flow-parallel">
            <a href="<%= u.email %>"><%= u.user_email %></a>
          </p>
          <p class="user-links-round icon-linkedin">
            <a href="<%= u.linkedin_url %>"><%= u.linkedin_url %></a>
          </p>
          <p class="user-links-round icon-behance">
            <a href="<%= u.behance_url %>"><%= u.behance_url %></a>
          </p>
          <p class="user-links-round icon-github">
            <a href="<%= u.github_url %>"><%= u.github_url %></a>
          </p>
          <p class="user-links-round icon-flow-parallel">
            <a href="<%= u.playstore_url %>"><%= u.playstore_url %></a>
          </p>
          <p class="user-links-round icon-twitter">
            <a href="<%= u.twitter_url %>"><%= u.twitter_url %></a>
          </p>
          <p class="user-links-round icon-pinterest">
            <a href="<%= u.pinterest_url %>"><%= u.pinterest_url %></a>
          </p>
      </div>

      </div>

      <div class="col-md-8">
        <section class="user-right">
          <h3>Bio</h3>
          <p><%= u.bio %></p>
          <h3>Skills</h3>
          <p><%= u.skills %></p>
          <%= link_to 'Edit', edit_user_path(@user) %> |
          <%= link_to 'Back', users_path %>
        </section>
      </div>
     <% end %>
   </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container new-form">
  <h1> New User </h1>
  <section class="row">
    <%= render 'form' %>
  </section>
</div>

app/views/users/show.html.erb
<div class="user-index">
  <div class="container">
    <div class="row">

     <h1 class="user-title">Hello  <%= @user.first_name %></h1>

      <div class="col-md-4">
        <section class="user-left">
          <div class="user-info">
          <% if @user.avatar_url.present? %>
            <%= image_tag @user.avatar_url, :class => 'user-img' %>
          <% else %>
          <% end %>
          <h3>First Name</h3>
          <p><%= @user.first_name %></h2>
          <h3>Last Name</h3>
          <p><%= @user.last_name %></p>
          <h3>Course</h3>
          <p><%= @user.course %></p>
          <h3>Age</h3>
          <p><%= @user.age %></p>
          <h3>Location</h3>
          <p><%= @user.location %></p>
        </div>
        <div class="user-links">
          <p class="user-links-round icon-flow-parallel">
            <a href="<%= @user.email %>"><%= @user.user_email %></a>
          </p>
          <p class="user-links-round icon-linkedin">
            <a href="<%= @user.linkedin_url %>"><%= @user.linkedin_url %></a>
          </p>
          <p class="user-links-round icon-behance">
            <a href="<%= @user.behance_url %>"><%= @user.behance_url %></a>
          </p>
          <p class="user-links-round icon-github">
            <a href="<%= @user.github_url %>"><%= @user.github_url %></a>
          </p>
          <p class="user-links-round icon-flow-parallel">
            <a href="<%= @user.playstore_url %>"><%= @user.playstore_url %></a>
          </p>
          <p class="user-links-round icon-twitter">
            <a href="<%= @user.twitter_url %>"><%= @user.twitter_url %></a>
          </p>
          <p class="user-links-round icon-pinterest">
            <a href="<%= @user.pinterest_url %>"><%= @user.pinterest_url %></a>
          </p>
      </div>

      </div>

      <div class="col-md-8">
        <section class="user-right">
          <h3>Bio</h3>
          <p><%= @user.bio %></p>
          <h3>Skills</h3>
          <p><%= @user.skills %></p>
          <%= link_to 'Edit', edit_user_path(@user) %> |
          <%= link_to 'Back', users_path %>
        </section>
      </div>
   </div>
  </div>
</div>